[build]
  command = "pip install -r requirements.txt"
  publish = "public"

[functions]
  external_node_modules = []
  node_bundler = "esbuild"
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
